### ISSUE TITLE
【Feature Request】Add ‘support number’ to the output

### ISSUE THREAD

**Issue by TimHe95** [Holy-Shine/PrefixSpan-py#1]
```
data = [
    [1, 4, 2, 3],
    [0, 1, 2, 3],
    [1, 2, 1, 3, 4],
    [2, 1, 2, 4, 4],
    [1, 1, 1, 2, 4],
]
 L = PrefixSpan.PrefixSpan(data,minSup=0.8,minConf=0)
```
Currently, the `L` is: `[[(1,), (4,), (2,), (0,)], [(1, 4), (1, 2)], []]`  
Could you please make it like `[[{(1,), 5}, {(4,), 4}, {(2,), 5}], [{(1, 4), 4}, {(1, 2), 5}], []]`

Thanks.

**Comment by Holy-Shine** [comment]
@TimHe95 Hello, sorry to reply to you so late, I have added this feature to the code according to your request. Have a try 😄
